[build]
	command = "npm run build"
	publish = "build"

[build.environment]
	NODE_VERSION = "18"

# Prevent caching of build files that might be stale
[[headers]]
	for = "/_app/immutable/*"
	[headers.values]
		Cache-Control = "public, immutable, max-age=31536000"
		Content-Type = "application/javascript; charset=utf-8"

[[headers]]
	for = "/_app/immutable/assets/*.css"
	[headers.values]
		Cache-Control = "public, immutable, max-age=31536000"
		Content-Type = "text/css; charset=utf-8"

[[headers]]
	for = "/_app/immutable/assets/*.js"
	[headers.values]
		Cache-Control = "public, immutable, max-age=31536000"
		Content-Type = "application/javascript; charset=utf-8"

[[headers]]
	for = "/*"
	[headers.values]
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"
		X-Content-Type-Options = "nosniff"

[[headers]]
	for = "/*.html"
	[headers.values]
		Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
	for = "/sw.js"
	[headers.values]
		Cache-Control = "public, max-age=0, must-revalidate"